In [2]:
import numpy as np

origin = np.array([100.0, 200.0, 300.0])

x_axis = np.array([1.0, 0.0, 0.0])
y_axis = np.array([0.0, 1.0, 0.0])
z_axis = np.array([0.0, 0.0, 1.0])

print(origin)
print(x_axis)
print(y_axis)
print(z_axis)

[100. 200. 300.]
[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]
