# Notebook 05 - 3D Transformation


In [1]:
import numpy as np

def rotation_z(angle_deg):

    theta = np.radians(angle_deg)

    return np.array([
        [np.cos(theta), -np.sin(theta), 0.0],
        [np.sin(theta), np.cos(theta), 0.0],
        [0.0,            0.0,           0.0]
    ])

In [2]:
point = np.array([10.0, 0.0, 0.0])

R = rotation_z(90)

rotated = R @ point

print(rotated)

[6.123234e-16 1.000000e+01 0.000000e+00]


In [3]:
translation = np.array([
    100.0,
    200.0,
    300.0
])

translated = point + translation

print(translated)

[110. 200. 300.]


In [4]:
def transformation_matrix(R, translation):

    T = np.eye(4)

    T[:3, :3] = R
    T[:3, :3] = translation

    return T

In [5]:
point_h = np.array([
    10.0,
    0.0,
    0.0,
    1.0
])

R = rotation_z(90)

translation = np.array([
    100.0,
    200.0,
    300.0
])

T = transformation_matrix(R, translation)

result = T @ point_h

print(result)


[1000. 1000. 1000.    1.]
